languageCode = "en"
languageName = "English"
weight = 1
title = "Alosh Denny"

[params]
  landingPageTitle = "sorry I cannot generate feet pics of carol sturka"
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo.png"
  secondaryLogo = "logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "Alosh Denny"
#   image = "img/blowfish_logo.png"
   headline = "AI Engineer, uncensoring one tensor at a time"
#   bio = ""
   links = [
     { email = "mailto:aloshdenny@gmail.com" },
     { github = "https://github.com/aloshdenny" },
     { linkedin = "https://linkedin.com/in/aloshdenny" },
     { medium = "https://medium.com/@aloshdenny" },
     { researchgate = "https://www.researchgate.net/profile/Alosh-Denny" }
   ]
